# Generated by Django 2.1.5 on 2019-02-01 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('IDMed', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('composicion', models.CharField(max_length=8)),
                ('fechaNacimiento', models.CharField(max_length=20)),
                ('gramosAingerir', models.DecimalField(decimal_places=2, max_digits=5)),
                ('numeroPastillas', models.DecimalField(decimal_places=2, max_digits=5)),
                ('usadoPara', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('pacienteId', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=8)),
                ('fechaNacimiento', models.CharField(max_length=20)),
                ('hijos', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.AddField(
            model_name='medicamento',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemas.Paciente'),
        ),
    ]
