# Generated by Django 2.1.5 on 2019-02-05 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemas', '0002_auto_20190205_0454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='hijos',
            field=models.IntegerField(),
        ),
    ]
